### ISSUE TITLE
Backport / Cherry-pick patch for MySQL 8.0 compatibility from upstream

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/mysqld_exporter#2]
These seem to be the related upstream pulls that fix this:
https://github.com/prometheus/mysqld_exporter/pull/307
https://github.com/prometheus/mysqld_exporter/pull/337

**Comment by oblitorum** [comment]
They are already picked at c4d7e1f2ef2872a3af1d30692ef6df248852a0f3 and c41775f3141de169ee95ea95d6c7011d1d1df69e
